### ISSUE TITLE
Code finds *additional* barcodes, filters existing

### ISSUE THREAD

**Issue by CowanCS1** [nh3/emptydrops#2]
I believe this code does not perform the task as expected. 

Specifically, it masks out the original cell barcodes such that the non_ambient calls are only made for the cells other than the originally supplied barcodes. In the CellRanger package (but not the code included here) this is followed by extending the set of original filtered barcodes:

```
# Update the lists of cell-associated barcodes
            for genome in genomes:
                eval_bc_strs = np.array(gg_matrix.bcs)[result.eval_bcs]
                filtered_bcs_groups[(gg, genome)].extend(eval_bc_strs[(genome_calls == genome) & (result.is_nonambient)])
```

This is a pretty specific behavior which doesn't perform what the user would expect based on R's emptydrops package (which notably does not require any pre-input of a starting barcode list). Curious to hear your thoughts.

**Comment by nh3** [comment]
Thanks for your feedback. The intention of this package is to give easy access to those code to replicate CellRanger's cell calling behaviour. So whether the behaviour matches exactly that of the R implementation was not given priority. In this particular case, `find_nonambient_barcodes()` finds *additional* non-ambient barcodes, which is the behaviour of this function in CellRanger. The reason I didn't further wrap the barcode merging part is that it's trivial for the user to do so, and it allows users to inspect the returned p values to choose an appropriate cutoff which provides more flexibility than just returning a set of barcodes.

**Comment by CowanCS1** [comment]
Fair enough, and I can understand why CellRanger would not want to evaluate and possibly exclude cell barcodes included with the previous method (even though this could perform poorly in some edge cases).

It would be very helpful if you add the description above to the readme, as the current description relies on knowing the details of CellRanger's emptydrops implementation. If the user doesn't have this knowledge a priori, they have to dig through the CellRanger code to understand that this is the expected behavior.

**Comment by nh3** [comment]
README updated in https://github.com/nh3/emptydrops/commit/45330a9116dc0da96498c3efab1706eb7fde9ae9
Thank you for your feedback and suggestion!
